"""Independent models for captured summary reports."""

from collections import defaultdict
from decimal import Decimal, ROUND_HALF_UP


_DURATION_BUCKETS = (
    ("0 - 30 seconds", None, 30, 30),
    ("31 - 60 seconds", 30, 60, 60),
    ("1 - 3 minutes", 60, 180, 180),
    ("3 - 5 minutes", 180, 300, 300),
    ("5 - 7 minutes", 300, 420, 420),
    ("7 - 10 minutes", 420, 600, 600),
    ("More than 10 minutes", 600, None, 900),
)

_VISITOR_TOOLTIPS = {
    "Visits": "A visit is a group of pageviews within a 30-minute time span. Returning visitors are counted multiple times if they start a new visit.",
    "Unique IPs": "It includes only traffic generated by human visitors.",
    "Bounce rate": "Total number of one-page visits divided by the total number of entries to a website. Please see the <a href=\"https://support.google.com/analytics/answer/1009409?hl=en\" target=\"_blank\">official Google docs</a> for more information.",
    "Known visitors": "Visitors who have previously left a comment on your blog.",
    "Single-page Visits": "Human users that generated one single page view on your website.",
}


def _window(rows, start, end, columns):
    if type(start) is not int or type(end) is not int or start > end:
        raise ValueError("summary window must be inclusive integer bounds")
    selected = []
    for index, row in enumerate(rows):
        if not isinstance(row, dict) or any(column not in row for column in columns + ("dt",)):
            raise ValueError("summary row %d lacks a consumed column" % index)
        if row["dt"] is not None and start <= row["dt"] <= end:
            selected.append(row)
    return selected


def _ascii_distinct(rows, column):
    values = set()
    for row in rows:
        value = row[column]
        if value is None:
            continue
        raw = value if isinstance(value, bytes) else value.encode("ascii")
        if any(byte > 127 for byte in raw):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        values.add(raw.rstrip(b" ").lower())
    return len(values)


def _visits(rows, human=False):
    return {row["visit_id"] for row in rows
            if row["visit_id"] is not None and row["visit_id"] > 0
            and (not human or (row["browser_type"] is not None and row["browser_type"] != 1))}


def bouncing_visits(rows, start, end):
    selected = _window(rows, start, end, ("id", "visit_id", "browser_type"))
    counts = defaultdict(int)
    for row in selected:
        if row["visit_id"] is not None and row["visit_id"] > 0 \
                and row["browser_type"] is not None and row["browser_type"] != 1:
            counts[row["visit_id"]] += row["id"] is not None
    return sum(count == 1 for count in counts.values())


def bouncing_pages(rows, start, end):
    selected = _window(rows, start, end, ("visit_id", "content_type", "resource"))
    counts = defaultdict(int)
    displays = {}
    for row in selected:
        if row["visit_id"] is None or row["visit_id"] <= 0 or row["content_type"] is None:
            continue
        content = row["content_type"] if isinstance(row["content_type"], bytes) \
            else row["content_type"].encode("ascii")
        if any(byte > 127 for byte in content):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        if content.rstrip(b" ").lower() == b"404":
            continue
        value = row["resource"]
        raw = value if isinstance(value, bytes) or value is None else value.encode("ascii")
        if raw is not None and any(byte > 127 for byte in raw):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        key = None if raw is None else raw.rstrip(b" ").lower()
        if key in displays and displays[key] != raw:
            raise ValueError("summary has an ambiguous collation-equivalent resource")
        displays[key] = raw
        counts[key] += 1
    return sum(count == 1 for count in counts.values())


def pages_per_visit(rows, start, end):
    selected = _window(rows, start, end, ("visit_id",))
    counts = defaultdict(int)
    for row in selected:
        if row["visit_id"] is not None and row["visit_id"] > 0:
            counts[row["visit_id"]] += 1
    if not counts:
        return [{"avghits": None, "maxhits": None}]
    average = (Decimal(sum(counts.values())) / len(counts)).quantize(Decimal("0.0001"), ROUND_HALF_UP)
    return [{"avghits": "%.4f" % average, "maxhits": str(max(counts.values()))}]


def visitors_summary(rows, start, end):
    selected = _window(rows, start, end, ("id", "visit_id", "browser_type", "ip", "username"))
    human = [row for row in selected
             if row["browser_type"] is not None and row["browser_type"] != 1]
    human_visits = _visits(human)
    visit_counts = defaultdict(int)
    for row in human:
        if row["visit_id"] is not None:
            visit_counts[row["visit_id"]] += row["id"] is not None
    singles = sum(count == 1 for count in visit_counts.values())
    total_visits = len({row["visit_id"] for row in human if row["visit_id"] is not None})
    bounce = Decimal(100 * singles) / total_visits if total_visits else Decimal(0)
    bounce_text = "100.00" if int(bounce) > 99 else "%.2f" % bounce.quantize(Decimal("0.01"), ROUND_HALF_UP)
    page_metrics = pages_per_visit(selected, start, end)[0]

    def formatted(value, places=0):
        if places:
            return f"{Decimal(value).quantize(Decimal('0.01'), ROUND_HALF_UP):,.2f}"
        return f"{int(value):,}"

    values = {
        "Visits": formatted(len(human_visits)),
        "Unique IPs": formatted(_ascii_distinct(
            [row for row in human if row["visit_id"] is not None and row["visit_id"] > 0], "ip")),
        "Bounce rate": bounce_text,
        "Known visitors": formatted(_ascii_distinct(selected, "username")),
        "Single-page Visits": formatted(singles),
        "Bots": formatted(sum(row["id"] is not None for row in selected if row["browser_type"] == 1)),
        "Pageviews per visit": formatted(page_metrics["avghits"] or 0, 2),
        "Longest visit": formatted(page_metrics["maxhits"] or 0) + " hits",
    }
    result = [{"metric": metric, "value": value} for metric, value in values.items()]
    for row in result:
        if row["metric"] in _VISITOR_TOOLTIPS:
            row["tooltip"] = _VISITOR_TOOLTIPS[row["metric"]]
    return sorted(result, key=lambda row: row["metric"])


def visit_duration(rows, start, end):
    if type(start) is not int or type(end) is not int or start > end:
        raise ValueError("visit-duration window must be inclusive integer bounds")

    visits = defaultdict(list)
    for index, row in enumerate(rows):
        if not isinstance(row, dict) or not all(
                column in row for column in ("visit_id", "browser_type", "dt", "dt_out")):
            raise ValueError("visit-duration row %d lacks a consumed column" % index)
        if row["visit_id"] is None or row["browser_type"] is None or row["dt"] is None:
            continue
        if row["visit_id"] > 0 and row["browser_type"] != 1 and start <= row["dt"] <= end:
            visits[row["visit_id"]].append(row)

    counts = [0] * len(_DURATION_BUCKETS)
    for rows_for_visit in visits.values():
        exits = [row["dt_out"] for row in rows_for_visit if row["dt_out"] is not None]
        if not exits:
            continue
        duration = max(max(row["dt"] for row in rows_for_visit), max(exits)) \
            - min(row["dt"] for row in rows_for_visit)
        for index, (_, low, high, _) in enumerate(_DURATION_BUCKETS):
            if (low is None or duration > low) and (high is None or duration <= high):
                counts[index] += 1
                break

    total = len(visits)
    result = []
    for (metric, _, _, weight), count in zip(_DURATION_BUCKETS, counts):
        percent = ("%.2f" % (Decimal(100 * count) / total).quantize(
            Decimal("0.01"), ROUND_HALF_UP)) if total else "0"
        result.append({"counthits": count, "details": "Hits: %d" % count,
                       "metric": metric, "value": percent + "%"})

    seconds = sum(bucket[3] * count for bucket, count in zip(_DURATION_BUCKETS, counts)) // total \
        if total else 0
    average = ("%02d:%02d:%02d" % (seconds // 3600, seconds // 60 % 60, seconds % 60)
               if seconds >= 3600 else "%02d:%02d" % (seconds // 60, seconds % 60)) \
        if total else "0:00"
    # Extended captures canonically order rows by their encoded object. Bucket
    # objects begin with counthits; the average object begins with details.
    result.sort(key=lambda row: (str(row["counthits"]), row["metric"]))
    result.append({"details": "", "metric": "Average Visit Duration", "value": average})
    return result
