"""Independent models for captured summary reports."""

from collections import defaultdict
from decimal import Decimal, ROUND_HALF_UP


_DURATION_BUCKETS = (
    ("0 - 30 seconds", None, 30, 30),
    ("31 - 60 seconds", 30, 60, 60),
    ("1 - 3 minutes", 60, 180, 180),
    ("3 - 5 minutes", 180, 300, 300),
    ("5 - 7 minutes", 300, 420, 420),
    ("7 - 10 minutes", 420, 600, 600),
    ("More than 10 minutes", 600, None, 900),
)

_VISITOR_TOOLTIPS = {
    "Visits": "A visit is a group of pageviews within a 30-minute time span. Returning visitors are counted multiple times if they start a new visit.",
    "Unique IPs": "It includes only traffic generated by human visitors.",
    "Bounce rate": "Total number of one-page visits divided by the total number of entries to a website. Please see the <a href=\"https://support.google.com/analytics/answer/1009409?hl=en\" target=\"_blank\">official Google docs</a> for more information.",
    "Known visitors": "Visitors who have previously left a comment on your blog.",
    "Single-page Visits": "Human users that generated one single page view on your website.",
}


def _window(rows, start, end, columns):
    if type(start) is not int or type(end) is not int or start > end:
        raise ValueError("summary window must be inclusive integer bounds")
    selected = []
    for index, row in enumerate(rows):
        if not isinstance(row, dict) or any(column not in row for column in columns + ("dt",)):
            raise ValueError("summary row %d lacks a consumed column" % index)
        if row["dt"] is not None and start <= row["dt"] <= end:
            selected.append(row)
    return selected


def _ascii_distinct(rows, column):
    values = set()
    for row in rows:
        value = row[column]
        if value is None:
            continue
        raw = value if isinstance(value, bytes) else value.encode("ascii")
        if any(byte > 127 for byte in raw):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        values.add(raw.rstrip(b" ").lower())
    return len(values)


def _visits(rows, human=False):
    return {row["visit_id"] for row in rows
            if row["visit_id"] is not None and row["visit_id"] > 0
            and (not human or (row["browser_type"] is not None and row["browser_type"] != 1))}


def bouncing_visits(rows, start, end):
    selected = _window(rows, start, end, ("id", "visit_id", "browser_type"))
    counts = defaultdict(int)
    for row in selected:
        if row["visit_id"] is not None and row["visit_id"] > 0 \
                and row["browser_type"] is not None and row["browser_type"] != 1:
            counts[row["visit_id"]] += row["id"] is not None
    return sum(count == 1 for count in counts.values())


def bouncing_pages(rows, start, end):
    selected = _window(rows, start, end, ("visit_id", "content_type", "resource"))
    counts = defaultdict(int)
    displays = {}
    for row in selected:
        # get_combined_where injects `resource IS NOT NULL` beside the caller's clause, so a
        # direct pageview (no resource) is not a bounce page however lonely its visit is.
        if row["visit_id"] is None or row["visit_id"] <= 0 or row["content_type"] is None \
                or row["resource"] is None:
            continue
        content = row["content_type"] if isinstance(row["content_type"], bytes) \
            else row["content_type"].encode("ascii")
        if any(byte > 127 for byte in content):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        if content.rstrip(b" ").lower() == b"404":
            continue
        value = row["resource"]
        raw = value if isinstance(value, bytes) or value is None else value.encode("ascii")
        if raw is not None and any(byte > 127 for byte in raw):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        key = None if raw is None else raw.rstrip(b" ").lower()
        if key in displays and displays[key] != raw:
            raise ValueError("summary has an ambiguous collation-equivalent resource")
        displays[key] = raw
        counts[key] += 1
    return sum(count == 1 for count in counts.values())


def pages_per_visit(rows, start, end):
    selected = _window(rows, start, end, ("visit_id",))
    counts = defaultdict(int)
    for row in selected:
        if row["visit_id"] is not None and row["visit_id"] > 0:
            counts[row["visit_id"]] += 1
    if not counts:
        return [{"avghits": None, "maxhits": None}]
    average = (Decimal(sum(counts.values())) / len(counts)).quantize(Decimal("0.0001"), ROUND_HALF_UP)
    return [{"avghits": "%.4f" % average, "maxhits": str(max(counts.values()))}]


def visitors_summary(rows, start, end):
    selected = _window(rows, start, end, ("id", "visit_id", "browser_type", "ip", "username"))
    human = [row for row in selected
             if row["browser_type"] is not None and row["browser_type"] != 1]
    human_visits = _visits(human)
    visit_counts = defaultdict(int)
    for row in human:
        if row["visit_id"] is not None:
            visit_counts[row["visit_id"]] += row["id"] is not None
    singles = sum(count == 1 for count in visit_counts.values())
    total_visits = len({row["visit_id"] for row in human if row["visit_id"] is not None})
    bounce = Decimal(100 * singles) / total_visits if total_visits else Decimal(0)
    bounce_text = "100.00" if int(bounce) > 99 else "%.2f" % bounce.quantize(Decimal("0.01"), ROUND_HALF_UP)
    page_metrics = pages_per_visit(selected, start, end)[0]

    def formatted(value, places=0):
        if places:
            return f"{Decimal(value).quantize(Decimal('0.01'), ROUND_HALF_UP):,.2f}"
        return f"{int(value):,}"

    values = {
        "Visits": formatted(len(human_visits)),
        "Unique IPs": formatted(_ascii_distinct(
            [row for row in human if row["visit_id"] is not None and row["visit_id"] > 0], "ip")),
        "Bounce rate": bounce_text,
        "Known visitors": formatted(_ascii_distinct(selected, "username")),
        "Single-page Visits": formatted(singles),
        "Bots": formatted(sum(row["id"] is not None for row in selected if row["browser_type"] == 1)),
        "Pageviews per visit": formatted(page_metrics["avghits"] or 0, 2),
        "Longest visit": formatted(page_metrics["maxhits"] or 0) + " hits",
    }
    result = [{"metric": metric, "value": value} for metric, value in values.items()]
    for row in result:
        if row["metric"] in _VISITOR_TOOLTIPS:
            row["tooltip"] = _VISITOR_TOOLTIPS[row["metric"]]
    return sorted(result, key=lambda row: row["metric"])


def visit_duration(rows, start, end):
    if type(start) is not int or type(end) is not int or start > end:
        raise ValueError("visit-duration window must be inclusive integer bounds")

    visits = defaultdict(list)
    for index, row in enumerate(rows):
        if not isinstance(row, dict) or not all(
                column in row for column in ("visit_id", "browser_type", "dt", "dt_out")):
            raise ValueError("visit-duration row %d lacks a consumed column" % index)
        if row["visit_id"] is None or row["browser_type"] is None or row["dt"] is None:
            continue
        if row["visit_id"] > 0 and row["browser_type"] != 1 and start <= row["dt"] <= end:
            visits[row["visit_id"]].append(row)

    counts = [0] * len(_DURATION_BUCKETS)
    for rows_for_visit in visits.values():
        exits = [row["dt_out"] for row in rows_for_visit if row["dt_out"] is not None]
        if not exits:
            continue
        duration = max(max(row["dt"] for row in rows_for_visit), max(exits)) \
            - min(row["dt"] for row in rows_for_visit)
        for index, (_, low, high, _) in enumerate(_DURATION_BUCKETS):
            if (low is None or duration > low) and (high is None or duration <= high):
                counts[index] += 1
                break

    total = len(visits)
    result = []
    for (metric, _, _, weight), count in zip(_DURATION_BUCKETS, counts):
        percent = ("%.2f" % (Decimal(100 * count) / total).quantize(
            Decimal("0.01"), ROUND_HALF_UP)) if total else "0"
        result.append({"counthits": count, "details": "Hits: %d" % count,
                       "metric": metric, "value": percent + "%"})

    seconds = sum(bucket[3] * count for bucket, count in zip(_DURATION_BUCKETS, counts)) // total \
        if total else 0
    average = ("%02d:%02d:%02d" % (seconds // 3600, seconds // 60 % 60, seconds % 60)
               if seconds >= 3600 else "%02d:%02d" % (seconds // 60, seconds % 60)) \
        if total else "0:00"
    # Extended captures canonically order rows by their encoded object. Bucket
    # objects begin with counthits; the average object begins with details.
    result.sort(key=lambda row: (str(row["counthits"]), row["metric"]))
    result.append({"details": "", "metric": "Average Visit Duration", "value": average})
    return result


_TRAFFIC_ROWS = (
    ("Pageviews",
     "A pageview is a request to load a single HTML page on your website."),
    ("Unique Referrers",
     "A referrer (or referring site) is a site that a visitor previously visited before following a link to your site."),
    ("Direct Pageviews",
     "Visitors who typed your website URL directly into their browser address bar. It can also refer to visitors who clicked on one of their bookmarked links, untagged links within emails, or links in documents that don't include tracking variables."),
    ("From External SERP",
     "Visitors who clicked on a link to your website listed on a search engine result page (SERP). This metric only counts visits coming from EXTERNAL search pages."),
    ("Unique Landing Pages",
     "A landing page is the first page on your website that a visitors opens, also known as <em>entrance page</em>. For example, if they search for 'Brooklyn Office Space,' and they land on a page on your website, this page gets counted (for that visit) as a landing page."),
    ("Bounce Pages",
     "Number of single-page visits tracked over the selected period of time."),
    ("New Visitors Rate",
     "Percentage of single-page visits, i.e. visits in which the person left your site from the entrance page."),
    ("Currently from search engines",
     "Visitors who clicked on a link to your website listed on a search engine result page (SERP), tracked in the last 5 minutes."),
)

_TRAFFIC_COLUMNS = ("id", "ip", "visit_id", "browser_type", "referer", "resource",
                    "searchterms", "content_type", "dt")


def _contains_ci(value, needle):
    """Case-insensitive substring containment, the way a wildcard match on both ends reads."""
    raw = value if isinstance(value, bytes) else value.encode("ascii")
    hay = needle if isinstance(needle, bytes) else needle.encode("ascii")
    if any(byte > 127 for byte in raw) or any(byte > 127 for byte in hay):
        raise ValueError("summary cannot model non-ASCII collation semantics")
    return hay.lower() in raw.lower()


def _counted(rows, column, distinct=False, absent=(), present=(), without=()):
    """Count a column over rows, after predicates whose unknown result drops the row.

    `absent` names columns that must have no value, `present` columns that must have one, and
    `without` pairs a column with a fragment it must not contain — a row with no value there
    fails that test too, because an unknown answer is not a true one.
    """
    kept = []
    for row in rows:
        if any(row[name] is not None for name in absent):
            continue
        if any(row[name] is None for name in present):
            continue
        if any(row[name] is None or _contains_ci(row[name], fragment)
               for name, fragment in without):
            continue
        if row[column] is not None:
            kept.append(row[column])
    if not distinct:
        return len(kept)
    values = set()
    for value in kept:
        raw = value if isinstance(value, bytes) else value.encode("ascii")
        if any(byte > 127 for byte in raw):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        values.add(raw.rstrip(b" ").lower())
    return len(values)


def traffic_sources_summary(rows, start, end, home_url, host):
    """Model get_traffic_sources_summary's eight rows over a pinned window.

    `home_url` and `host` come from the capture, not from a static contract: the container
    picks its HTTP port at run time, so a literal baked into the contract would model a
    different site than the one that was measured.
    """
    if not isinstance(home_url, str) or not home_url or not isinstance(host, str) or not host:
        raise ValueError("traffic-sources summary requires the captured self URLs")
    selected = _window(rows, start, end, _TRAFFIC_COLUMNS)

    # Row 7 alone is asked WITHOUT the date filter and against the wall clock — the last five
    # minutes before the report ran. Capture runs at or after the window's end, which is the
    # corpus's own newest timestamp, so every row that report could still see lies inside
    # "newer than the window's end minus five minutes". An empty superset proves the answer is
    # 0; anything else means the corpus reaches the live tail and this row has no clock-free
    # model, so the model refuses rather than guessing.
    tail = [row for row in rows if row["dt"] is not None and row["dt"] > end - 300]
    if _counted(tail, "id", present=("searchterms", "referer"), without=(("referer", home_url),)):
        raise ValueError("corpus reaches the live five-minute tail; this row is clock-bound")

    pageviews = _counted(selected, "id")
    total_human_hits = len([row for row in selected
                            if row["visit_id"] is not None and row["visit_id"] > 0
                            and row["browser_type"] is not None and row["browser_type"] != 1
                            and row["id"] is not None])
    # The report's own clause is `visit_id > 0`; the shared where-builder adds "and the address
    # is present" because the address is what the rows group by.
    visits_per_ip = defaultdict(int)
    for row in selected:
        if row["ip"] is None or row["visit_id"] is None or row["visit_id"] <= 0:
            continue
        raw = row["ip"] if isinstance(row["ip"], bytes) else row["ip"].encode("ascii")
        if any(byte > 127 for byte in raw):
            raise ValueError("summary cannot model non-ASCII collation semantics")
        visits_per_ip[raw.rstrip(b" ").lower()] += 1
    new_visitors = sum(count == 1 for count in visits_per_ip.values())

    rate = (Decimal(100 * new_visitors) / total_human_hits).quantize(
        Decimal("0.01"), ROUND_HALF_UP) if total_human_hits else Decimal(0)
    # The product clamps on the truncated value, not the rounded one: 99.6 prints as itself,
    # 100.4 prints as 100.00.
    rate_text = "100.00" if int(rate) > 99 else f"{rate:,.2f}"

    values = [
        f"{pageviews:,}",
        "{:,}".format(_counted(selected, "referer", True, without=(("referer", host),))),
        "{:,}".format(_counted(selected, "id", absent=("resource",))),
        "{:,}".format(_counted(selected, "id", present=("searchterms", "referer"),
                               without=(("referer", home_url),))),
        "{:,}".format(_counted(selected, "resource", True)),
        f"{bouncing_pages(rows, start, end):,}",
        rate_text,
        "0",
    ]
    return [{"metric": metric, "tooltip": tooltip, "value": value}
            for (metric, tooltip), value in zip(_TRAFFIC_ROWS, values)]
